//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerTran
    {
        public long TransId { get; set; }
        public string VoucharNo { get; set; }
        public string AccountNo { get; set; }
        public string CurrencyCode { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> TransType { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<decimal> TransAmount { get; set; }
        public string Currency { get; set; }
        public string ExchangeVat { get; set; }
        public string FinancialDimension { get; set; }
        public string settlementType { get; set; }
        public Nullable<System.DateTime> DeuDate { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public Nullable<int> TransStatusId { get; set; }
        public Nullable<long> RECID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
