//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustTransOpen
    {
        public long TransOpenId { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> AmtCurrency { get; set; }
        public Nullable<decimal> AmountMst { get; set; }
        public Nullable<System.DateTime> DeuDate { get; set; }
        public Nullable<long> RefRecId { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<long> RecId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
