//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiscountGroupLine
    {
        public long DisLineId { get; set; }
        public Nullable<long> DiscountGroupId { get; set; }
        public Nullable<long> ItemTypeId { get; set; }
        public Nullable<long> Itemvalue { get; set; }
        public Nullable<long> PartnerTypeId { get; set; }
        public Nullable<long> PartnerTypeValue { get; set; }
        public Nullable<long> EntityId { get; set; }
        public Nullable<long> CountryId { get; set; }
        public Nullable<System.DateTime> Fromdate { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public Nullable<decimal> FromQty { get; set; }
        public Nullable<decimal> ToQty { get; set; }
        public Nullable<long> DiscountModeId { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
