//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public long ItemId { get; set; }
        public string AXItemid { get; set; }
        public string ItemName { get; set; }
        public string ItemGroup { get; set; }
        public string ItemUnit { get; set; }
        public Nullable<decimal> AvailPhysical { get; set; }
        public string InventLocationId { get; set; }
        public Nullable<bool> IsSellable { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
