//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public long InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public string Description { get; set; }
        public Nullable<long> PartnerId { get; set; }
        public Nullable<long> BillingLocId { get; set; }
        public Nullable<long> ShippingLocId { get; set; }
        public Nullable<long> EntityId { get; set; }
        public Nullable<long> CountryId { get; set; }
        public Nullable<long> TaxTypeId { get; set; }
        public Nullable<decimal> TotalWithTax { get; set; }
        public Nullable<decimal> TotalWithoutTax { get; set; }
        public Nullable<decimal> SumOfQty { get; set; }
        public Nullable<decimal> SumOfUnitPrice { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> Duedate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
