//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMstitem1
    {
        public long Itemid { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> ItemGroup { get; set; }
        public Nullable<int> ItemType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> CartPrice { get; set; }
        public Nullable<bool> Isvariant { get; set; }
        public Nullable<int> Itemtracking { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> Countryid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
