//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMstunitconversion
    {
        public int CUid { get; set; }
        public Nullable<decimal> FactorValue { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> FromUnit { get; set; }
        public Nullable<int> ToUnit { get; set; }
        public Nullable<int> Unittype { get; set; }
        public Nullable<int> Unitclass { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
