//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequisitionItemDetail
    {
        public int RequestDetId { get; set; }
        public int RequisitionId { get; set; }
        public Nullable<long> ItemSKUId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public string AXitemId { get; set; }
        public string RequestedWareHouse { get; set; }
        public Nullable<decimal> RequestedQty { get; set; }
        public Nullable<decimal> ApprovedQty { get; set; }
        public Nullable<decimal> ShippedQty { get; set; }
        public Nullable<long> ReceivedQty { get; set; }
        public Nullable<decimal> RemainingQty { get; set; }
        public string TransferOrder { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<long> ShippedBY { get; set; }
        public Nullable<long> ReceiveBy { get; set; }
        public Nullable<long> LineStatus { get; set; }
        public string ShipingReason { get; set; }
        public string ReceivingReason { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> shippedDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<bool> ApprovedFlag { get; set; }
        public Nullable<int> ShippingFlag { get; set; }
    }
}
