//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserLogin
    {
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<long> CountryId { get; set; }
        public Nullable<long> PartnerId { get; set; }
        public Nullable<long> EntityId { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> MobileNo { get; set; }
        public Nullable<int> UserRole { get; set; }
        public string Password { get; set; }
        public string PasswordKey { get; set; }
        public Nullable<long> WareHouseId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
