//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempFileSequenceline
    {
        public int Seqlineid { get; set; }
        public Nullable<long> Seqheadid { get; set; }
        public Nullable<long> Sequencetype { get; set; }
        public Nullable<long> Fixedno { get; set; }
        public Nullable<long> Placeofdigits { get; set; }
        public string Value { get; set; }
        public Nullable<long> Increementvalue { get; set; }
        public Nullable<int> SeqLength { get; set; }
        public Nullable<int> RemainCount { get; set; }
        public Nullable<int> Dateformat { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
